# Proyecto Final ML23

In [2]:
import numpy as np
import random
import gymnasium as gym
import time

In [7]:
from gym.envs.toy_text.frozen_lake import generate_random_map #Utilizar esto para generar mapas y evaluar al agente entrenado

def run():
    env = gym.make('FrozenLake-v1', desc=None, render_mode="human" ,map_name="4x4", is_slippery=False)
    
    state = env.reset()[0] #Estados 0 al 15, 0=top left, 15=bottom left 
    hoyo = False
    perdido = False
    analisis = env.observation_space
    interacion = 0

    while(not hoyo):
        action = env.action_space.sample() #acciones 0=izq,1=abajo,2=der,3=arriba
        info = env.step(action)
        new_state,reward,hoyo,_,_= info

        state = new_state
        interacion = interacion + 1
        
        print("Interacion numero: "+ str(interacion)+" hizo la accion numero: "+str(action))
        print(info)
        env.render()
        time.sleep(7)
        
    env.close()
    
    print(analisis)
run() #corre el Frozen Lake

Interacion numero: 1 hizo la accion numero: 1
(4, 0.0, False, False, {'prob': 1.0})
Interacion numero: 2 hizo la accion numero: 0
(4, 0.0, False, False, {'prob': 1.0})
Interacion numero: 3 hizo la accion numero: 3
(0, 0.0, False, False, {'prob': 1.0})
Interacion numero: 4 hizo la accion numero: 0
(0, 0.0, False, False, {'prob': 1.0})
Interacion numero: 5 hizo la accion numero: 1
(4, 0.0, False, False, {'prob': 1.0})
Interacion numero: 6 hizo la accion numero: 2
(5, 0.0, True, False, {'prob': 1.0})
Discrete(16)


In [8]:
#Qtable Printout
qtable = np.zeros((16,4))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
